spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth:9081
          predicates:
            - Path=/api/auth/login
          filters:
            - StripPrefix=1

        - id: joke-service
          uri: http://joke:9082
          predicates:
            - Path=/api/jokes/**
          filters:
            - StripPrefix=1

        - id: quote-service
          uri: http://quote:9083
          predicates:
            - Path=/api/quotes/**
          filters:
            - StripPrefix=1
